FROM alpine:3.7

EXPOSE 80

ARG livezilla_ver
ARG archive_url

ENV livezilla_ver 8.0.0.8
ENV archive_url ${archive_url:-https://www.livezilla.net/downloads/pubfiles/livezilla_server_${livezilla_ver}.zip}

RUN apk update && \
    apk add --no-cache \
    mysql-client \
    php7-mysqli apache2 \
    wget sqlite git curl bash grep \
    supervisor

